import turtle
t = turtle.Pen()
h = turtle.window_height()
w = turtle.window_width()
turtle.bgcolor("blue")
t.pencolor("yellow")
t.pensize(50)
t.forward(w//2)
t.back(w)
t.forward(w//4)
t.left(90)
t.forward(h//2)
t.back(h)
quit()